### ISSUE TITLE
Question on Running in Dev Mode

### ISSUE THREAD

**Issue by LinguList** [knightss27/capr#17]
@knightss27, I am sorry to bother you, but while I can load the two server instances both for the instance that serves the JSON and the one that provides the GUI, I cannot have them communicate with each other due to violations against cross-server accesses. 

The instructions tell me to load the two instances (flaks and node) independently. So flask serves at localhost:5000 or similar and node serves at localhost:8080 or similar. As a result, the node server now cannot access the flask server, which according to the application is expected to serve at `/api/refish-board` (for example). 

So my question is: what am I doing wrong, or how do I combine both server instances here?

And my apologies in advance if this question is stupid and there is just a very simple solution I did not know about.

**Comment by knightss27** [comment]
Hmm yes, it seems I didn't write the original dev instructions very well. You're right that doing it as so will run into CORS issues. I think the fix here is to use Caddy, which I seem to have only written as useful for production usage, but I believe I developed with it on as well. My bad. This is what fixes the "/api/" problem as well, as Caddy can redirect those requests to the :5000 port (thus avoiding CORS restrictions while still allowing separate instances). I think the existing Caddyfile (present in the repo) needs to be changed to work for development, as the ports are different for the development processes. If you can get it to work yourself with this guidance then great, otherwise later today I will get back to you with a specific Caddyfile that works, as I'm away from my computer right now.

**Comment by knightss27** [comment]
Ok double checked to make sure, but this Caddyfile works for serving CAPR on localhost:5001, assuming you've started the GUI and server as development. Note that you can change the port at the beginning to whatever you'd like, as long as it isn't either of the other two ports (though these are configurable through Flask/Svelte as well if you really needed it on :5000 for example).

```
:5001

route /api/* {
    uri strip_prefix /api
    reverse_proxy :5000
}

reverse_proxy :8080
```

After you've changed the Caddyfile, just make sure to do 

```
caddy adapt
caddy run
```

**Comment by LinguList** [comment]
Super, I'll test this ASAP, many thanks!

**Comment by LinguList** [comment]
Perfect, I can confirm this works. This means I have now full debug access and could try and set this up for another language family as an example. Many thanks!
